### ISSUE TITLE
RunTime error while trying to convert geographic coordinates to geomagnetic

### ISSUE THREAD

**Issue by bcmartinez38** [aburrell/aacgmv2#75] opened 2022-06-27 00:21 UTC
Hi, I'm having issues converting some coordinates that should be straightforward based on the documentation. I am converting a full globe worth of data points, but for some reason I am getting a runtime error on most (but not all) points. For example, 

`unable to perform conversion at 17.5,8.8 300.0 km, 2020-02-17 00:00:00 using method 4: <class 'RuntimeError'>`

I tried with every method and at different arbitrary dates/heights and got similar results . 
**To Reproduce**
Run, for example, 

```
import aacgmv2
import datetime as dt
import numpy as np
dtime = dt.datetime(2013, 1, 1)
print(np.array(aacgmv2.get_aacgm_coord(20.0,15.0, 300, dtime))
```

**Expected behavior**
I expected it to output the converted coordinates

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version 22.04

**Comment by aburrell** [comment] 2023-01-20 23:38
Ok, Running the example (modified to add the final closing paren), I get: `[10.60838521 87.51688091  0.61967014]`.

However, using locations/times in the error I can reproduce the problem.  It looks like the issue is that you're trying to convert near the equator, where AACGMV2 is not fully defined.  Can you confirm that the issue happens only at low latitudes?

**Comment by aburrell** [comment] 2023-01-23 15:57
I can confirm that AACGM is not defined here after checking the Dartmouth calculator: http://sdnet.thayer.dartmouth.edu/aacgm/aacgm_calc.php#AACGM.  I will look into improving the error message so that this possibility is clearer.

**Closed** 2023-01-24 21:48 UTC
